version: '3.4'

services:
  nodejspongservice:
    image: nodejspongservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
